version: '3'

services:
  multicraft:
    build: 
      context: ../
      args:
        - USERID=99
        - GROUPID=100
        - USERNAME=multicraft
    restart: always
    ports:
      - "8080:80"
      - "2111:21"
      - "25565:25565"
    environment:
      - MC_FTP_IP=0.0.0.0
      - MC_FTP_PORT=21
      - MC_KEY=no
      - MC_DAEMON_PW=ChangeMe
      #- MC_DB_ENGINE=sqlite
      - MC_DB_ENGINE=mysql
      - MC_DB_HOST=db
      - MC_DB_USER=mc_user
      - MC_DB_PASSWORD=multicraft1234!
      - MC_MULTIUSER=y
    volumes:
      - ../multicraftData:/multicraft
    depends_on:
      - "db"

  db:
    image: mysql:latest
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
    volumes:
      - ../db:/var/lib/mysql
      - ../setup/mysqlinit.sql:/docker-entrypoint-initdb.d/mysqlinit.sql
    restart: always
    ports:
      - "3306:3306" 
    environment:
      MYSQL_ROOT_PASSWORD: abcD1234!
